version: '3.7'

services:
  frontend:
    image: vitalymegabyte/ntindex_frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_BASEURL=62.109.24.120:5000
    ports:
      - 3000:3000
    stdin_open: true

  backend:
    image: vitalymegabyte/ntindex_backend
    command: python -m flask run -h 0.0.0.0 -p 5000
    depends_on:
      - db
    ports:
      - 5000:5000
    environment: 
      - FLASK_APP=main.py
      - FLASK_ENV=development

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment: 
      - MYSQL_USER=vitaly
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=0
      - MYSQL_DATABASE=ntindex
