"""empty message

Revision ID: 5d74cce798dc
Revises: 
Create Date: 2020-11-28 20:16:38.900670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d74cce798dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('gp_link', sa.String(length=1000), nullable=True),
    sa.Column('appstore_link', sa.String(length=1000), nullable=True),
    sa.Column('msstore_link', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('range_factor', sa.String(length=100), nullable=False),
    sa.Column('show_in_list', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags_relations',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_relations')
    op.drop_table('tag')
    op.drop_table('application')
    # ### end Alembic commands ###
