"""empty message

Revision ID: b46e248fec20
Revises: 0922a9ce3099
Create Date: 2020-11-28 07:25:24.489056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46e248fec20'
down_revision = '0922a9ce3099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('range_factor', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'range_factor')
    # ### end Alembic commands ###
