"""empty message

Revision ID: f6b08acc0610
Revises: b46e248fec20
Create Date: 2020-11-28 08:11:14.428286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6b08acc0610'
down_revision = 'b46e248fec20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('show_in_list', sa.Boolean(), nullable=False))
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tag', 'range_factor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'range_factor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('tag', 'show_in_list')
    # ### end Alembic commands ###
