export const ApplicationsActionTypes = {
  SET_APPLICATIONS: 'SET_APPLICATIONS',
  SET_CURRENT_APPLICATION_ID: 'SET_CURRENT_APPLICATION_ID',
  SET_SHOW_WINDOW: 'SET_SHOW_WINDOW',
  RESET_APPLICATIONS_STATE: 'RESET_APPLICATIONS_STATE',
};
